In [1]:
# 高频数据接口
# from HighFrequencyData_test import *
# hfd = HighFrequencyData_test()
# from HighDataCheck_test import *
from QSEnvironment import QSEnv
MainQSEnv = QSEnv()
MainQSEnv.startQS()

import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

c:\users\quantstudio\appdata\local\programs\python\python36\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\users\quantstudio\appdata\local\programs\python\python36\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
c:\users\quantstudio\appdata\local\programs\python\python36\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)

In [27]:
# 获取因子表列表
TableList = MainQSEnv.FactorDB.getTableName()
filtered = [i for i in TableList if 'StyleFactor' in i]
TableList.sort()
print(filtered)
# print(TableList)

['StyleFactor', 'HFFStyleFactorW', 'ty_zz800StyleFactors', 'PCI_EStyleFactor_Synthesis', 'CBondStyleFactor', 'ty_A500StyleFactors', 'StyleFactorNew', 'PCI_EStyleFactor_Synthesis_zs', 'hzy_StyleFactor_TF', 'hzy_StyleFactor_IF', 'StyleFactorI', 'StyleFactorI_Part', 'StyleFactor_IF_New', 'StyleFactor_TF_New', 'StyleFactorI_New', 'StyleFactorG10D260R1', 'ty_A500StyleFactors6', 'StyleFactorT', 'StyleFactorM']

In [2]:
#查看因子表名
FactorList = MainQSEnv.FactorDB.getFactorName('ElementaryFactor_ETF')
FactorList.sort()
print(FactorList)

['jscc_testetf', '复权均价', '复权开盘价', '复权收盘价', '复权最低价', '复权最高价', '成交量', '成交额', '投资范围', '是否停牌', '港股通ETF收盘价', '等权基准复权收盘价', '贴水率']

In [29]:
# 查看因子表数据
data = MainQSEnv.FactorDB.loadFactor(
    table_name='StyleFactorM',
    factor_name='StyleFactorM',
    start_date=None,
    end_date=None,
    dates=None,
    ids=None)

#data.columns = ['20250630','']
#data.T.dropna().to_csv('沪深300成分权重.csv')
# pq.write_table(pa.Table.from_pandas(data),'investtype_25.pqt')

#sw3_data.head()consensus
#col_names=zxIndust_data.columns
#with open('col_names.txt', 'w') as f:
    #for col in col_names:
       # f.write(col + '\n')
#print(zxIndust_data.columns.tolist())

# pq.read_table('prices.pqt').to_pandas()
#sw3_data.to_csv('sw_third.csv', encoding='gbk')
# data.to_csv('收盘价.csv')
data#.T.dropna().to_csv('沪深300权重2507-08.csv')

,000001.SZ,000002.SZ,000003.SZ,000004.SZ,000005.SZ,000006.SZ,000007.SZ,000008.SZ,000009.SZ,000010.SZ,...,920970.BJ,920971.BJ,920974.BJ,920976.BJ,920978.BJ,920981.BJ,920982.BJ,920985.BJ,920992.BJ,T00018.SH
20240102,-0.516612,-0.647021,NaN,0.311504,-0.203552,-0.078486,1.103015,0.140744,0.301603,-0.840881,...,-0.693138,-1.882763,-1.307980,1.058961,-0.499951,-0.741400,-0.633686,-1.199200,-1.094378,NaN
20240108,-0.524888,-0.728549,NaN,-0.315163,-0.169634,0.038024,1.134928,0.058354,0.259545,-1.218929,...,-0.800019,-1.708176,-1.238011,1.131339,-0.400778,-0.743409,-0.553836,-1.281874,-0.862052,NaN
20240115,-0.326159,-0.471398,NaN,-0.441541,-0.269415,-0.044852,1.553447,0.568681,0.022184,-1.872093,...,-0.984647,-1.471973,-1.340164,1.220254,0.106868,-0.362216,-0.800432,-0.783639,-0.152564,NaN
20240122,-0.069409,-0.512205,NaN,-0.417564,-0.361066,-0.337996,1.112434,0.457020,-0.156803,-1.507963,...,-1.029556,-1.686695,-1.328877,0.601473,-0.451267,-1.132811,-0.653756,-1.078056,-0.807225,NaN
20240129,0.003538,-0.472957,NaN,-0.815228,-0.260221,-0.189575,0.794361,0.062069,-0.608993,-1.536612,...,-0.830448,-1.410944,-1.237653,1.020107,-0.109417,-0.995030,-0.669760,-0.547106,-1.782251,NaN
20240205,0.041270,-0.312692,NaN,-0.482278,-0.208260,-0.107004,0.271356,0.298364,-0.685482,-1.848554,...,-0.793991,-1.164166,-1.224789,0.967798,-0.560069,-1.243981,-0.714398,-0.924277,-1.977648,NaN
20240219,0.275655,-0.534650,NaN,0.065328,0.130223,-0.102698,0.600552,0.829659,-1.536994,-1.413904,...,-1.021389,-1.150578,-1.233034,1.380138,-0.697751,-1.259680,-0.442220,-0.995525,-1.764423,NaN
20240226,-1.329401,-0.514636,NaN,0.222169,-0.638819,0.121672,0.458914,1.245222,-1.338581,-1.274405,...,-0.933969,-1.113892,-0.924533,-0.034179,-0.324968,-0.940551,-0.654505,-0.483670,-1.566852,NaN
20240304,-1.199570,-0.413469,NaN,-0.266069,-0.918177,0.034880,0.628026,1.575040,-1.176661,-0.709366,...,-0.919615,-0.859416,-1.428235,-0.040068,-0.633776,-0.551743,-0.343593,-1.036716,-1.229122,NaN
20240311,-1.235162,-0.399138,NaN,-0.674046,-0.705734,0.585536,0.069331,-1.642035,-1.131713,-0.994875,...,-0.977250,-0.577722,-1.423027,0.057525,-0.503534,-0.357122,-0.578836,-0.892617,-0.716658,NaN
20240318,-1.719484,-0.627604,NaN,-1.049011,-0.270658,0.825284,-0.064831,-1.878313,-0.585692,-1.073839,...,-0.650140,-0.640277,-1.292880,0.297148,0.387097,-0.070498,-0.384052,-0.633352,-0.482415,NaN
20240325,-1.301836,-0.577079,NaN,-0.873529,-0.396098,0.819609,-0.224897,-1.789909,-0.452797,-0.963294,...,-0.752880,-0.441865,-1.283374,1.495731,0.520675,0.077084,0.142485,-0.553319,-0.123003,NaN
20240401,-1.117986,-0.863361,NaN,-1.068344,0.022605,0.827015,-0.214482,-1.801804,-0.302147,-0.972446,...,-0.583366,-0.052294,-0.213037,2.259397,0.543080,0.437886,0.084865,0.413653,0.665795,NaN
20240408,-1.082854,-0.758314,NaN,-0.860895,1.115582,1.072757,-0.154065,-1.783199,0.008944,-0.747689,...,-0.523860,0.187022,-0.001883,2.208204,0.750181,0.785582,0.376337,0.685017,0.939976,NaN
20240415,-1.051486,-0.698462,NaN,-0.467247,0.890158,0.884578,0.076303,-1.257534,0.283740,-0.419482,...,-0.262736,-0.050370,-0.036240,1.440892,0.506451,0.393925,0.336575,1.013007,-0.036711,NaN
20240422,-0.901274,-0.679817,NaN,0.060986,0.814238,0.991114,-0.030361,-1.034342,0.052029,-0.155703,...,-0.205940,0.447745,0.387146,1.344046,1.050548,0.503080,0.367940,0.725605,-1.013671,NaN
20240429,-0.830469,-0.905971,NaN,0.444804,NaN,0.081305,0.417934,-0.701634,-0.019540,-0.241260,...,-0.731456,1.247925,1.395559,1.801890,1.413229,1.353188,-0.183944,1.134974,-0.687849,NaN
20240506,-0.868288,-0.920977,NaN,0.000706,NaN,0.332042,0.631657,-1.336902,-0.057235,-0.123431,...,-1.002472,1.285737,1.109348,1.804282,1.414509,1.513450,-0.086030,2.224599,-0.486788,NaN
20240513,-0.830075,-0.759710,NaN,-0.527265,NaN,0.491895,0.766638,-1.356932,0.396293,-0.215082,...,-1.035146,1.577327,1.290266,1.693756,1.455566,1.217946,0.023299,2.648976,-0.096868,NaN
20240520,-1.033539,-1.146028,NaN,-1.214987,NaN,0.433742,1.261587,-1.220916,0.313568,-0.260595,...,-0.767269,0.533766,1.844213,1.747514,1.904149,1.626561,-0.252327,2.699372,0.519708,NaN
20240527,-0.804442,-1.114822,NaN,-0.936448,NaN,0.506287,1.305563,-1.191689,0.230521,-0.127179,...,-0.663892,0.025653,1.637255,2.111431,1.012099,1.107840,-0.250384,1.494679,0.427029,NaN
20240603,-0.828747,-1.008962,NaN,-0.818178,NaN,0.525643,1.026340,-1.016034,0.045904,0.202095,...,-0.468655,0.142853,1.946177,2.464869,0.956334,1.359299,-0.092140,1.536223,0.262543,NaN
20240611,-0.901981,-1.139698,NaN,-0.497746,NaN,0.444106,0.861710,-0.545744,-0.572154,-0.142378,...,0.375505,-0.182439,1.802061,2.882692,0.588865,0.944505,-0.218937,1.234919,0.449827,NaN
20240617,-0.399683,-0.985621,NaN,0.018830,NaN,0.419135,0.570889,-0.412976,-0.660813,-0.040965,...,-0.190856,0.135513,1.870543,3.080616,0.414001,1.023830,-0.156923,1.348602,0.433570,NaN
20240624,-0.222994,-0.810447,NaN,-0.587901,NaN,-0.857757,0.121702,-0.537186,-0.663454,-1.597325,...,-0.635563,0.446875,2.129330,2.914137,0.698462,1.726333,0.031532,1.585638,0.021647,NaN
20240701,-0.176494,-0.788148,NaN,-1.138682,NaN,-0.835933,0.556542,-0.516854,-0.670211,-1.615958,...,-0.517930,1.110336,2.157254,3.030522,0.543400,2.023664,0.069724,2.664970,-0.142167,NaN
20240708,-0.334347,-0.446194,NaN,-0.977749,NaN,-0.796895,-1.220585,-0.238640,-0.379014,-1.764857,...,-0.679375,1.168680,2.045897,3.308098,0.399332,2.235849,-1.051006,2.699184,0.298699,NaN
20240715,-0.493561,-0.903325,NaN,-1.245440,NaN,-0.793251,-1.146250,-0.498356,-0.138257,-1.806344,...,-0.948166,1.001980,0.690249,3.307940,0.960797,2.409430,-1.411549,2.495049,0.366358,NaN
20240722,-0.432020,-1.198603,NaN,-1.543261,NaN,-0.199239,-1.147045,-1.647503,0.124735,-1.511490,...,-0.714223,-0.185797,0.158533,1.523412,0.158056,-1.158032,-1.025489,1.693131,0.077364,NaN
20240729,-0.448295,-1.234943,NaN,-1.409972,NaN,-0.412607,-1.227900,-1.991238,0.110067,-1.632846,...,-0.660792,-0.047633,0.187787,1.589688,0.302499,-0.949264,-0.940424,1.880821,0.065104,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20250512,0.539325,-2.139201,NaN,0.996882,NaN,0.712885,0.169605,-1.128355,0.185172,0.394740,...,0.215970,-0.683847,0.293213,0.765366,-0.172904,-0.373743,-1.246758,0.143749,-0.921127,NaN
20250519,0.292021,-1.927889,NaN,0.951126,NaN,0.025292,0.148801,-0.969523,0.469843,0.456413,...,0.333933,-1.014298,0.287666,0.784089,0.040613,0.073148,-1.147432,-0.101096,-0.434889,NaN
20250526,1.313427,-1.730712,NaN,0.589333,NaN,-0.234652,-0.076187,-0.937952,0.395262,0.491033,...,0.422509,-0.882470,0.556519,0.496275,0.414404,0.060835,-1.189569,-0.057116,-0.910212,NaN
20250603,0.979479,-1.477670,NaN,0.348958,NaN,-0.295153,0.325854,-1.048587,0.669252,0.529148,...,0.036925,-1.052619,0.464003,0.861036,0.609992,-0.002090,-0.867106,-0.104439,0.098838,NaN
20250609,0.903339,-1.346109,NaN,0.695021,NaN,-0.351649,0.277525,-0.936638,0.759093,0.084785,...,0.223889,-0.928752,0.543182,1.207764,0.743097,0.244875,-0.784720,-0.053620,-0.179372,NaN
20250616,1.166683,-1.762972,NaN,1.069623,NaN,-0.284657,0.471728,-0.207189,0.603649,0.155785,...,0.204346,-0.767440,0.697674,1.141406,0.626628,0.535985,-0.531706,0.622682,0.165182,NaN
20250623,1.110170,-1.845755,NaN,1.427805,NaN,-0.063334,0.570347,-0.327310,-0.332206,0.245646,...,0.083791,-1.025703,0.832210,1.241580,0.343005,0.626928,-0.255215,0.770832,0.037335,NaN
20250630,0.586638,-1.668169,NaN,1.818353,NaN,0.490116,0.857924,0.071480,-0.533468,0.348240,...,0.368516,-1.500848,0.993926,1.321577,0.202651,0.099874,-0.722283,0.735591,0.326150,NaN
20250707,0.555749,-1.623084,NaN,1.825503,NaN,0.421329,1.423664,0.046410,-0.576990,0.663031,...,0.859003,-1.602643,1.408491,1.435263,0.313579,0.089193,-0.769795,0.294630,0.442721,NaN
20250714,0.383098,-1.609382,NaN,2.079497,NaN,0.868435,1.961788,0.096182,-0.337550,-1.009773,...,0.208413,-1.529902,0.089659,1.560517,0.418289,0.447843,-0.712400,0.048268,0.359241,NaN
20250721,0.450074,-1.408292,NaN,2.099940,NaN,0.969400,1.971255,0.279266,0.057581,-1.064353,...,0.179170,-1.431178,-0.151880,1.500466,0.767026,0.289898,-0.375765,0.397270,0.493653,NaN
20250728,0.437440,-1.128810,NaN,1.924922,NaN,0.968039,1.584384,0.296382,0.189756,-0.995082,...,-0.193537,-1.196296,-0.206793,2.075406,1.127933,0.435909,0.370966,0.151617,0.213909,NaN
20250804,0.442209,-0.877262,NaN,2.071500,NaN,1.121061,1.374294,0.497651,0.205569,-1.259506,...,-0.363698,-1.278184,-0.156988,2.219293,1.552726,1.161092,1.143075,0.299963,0.593508,NaN
20250811,0.448179,-0.670275,NaN,2.533721,NaN,0.259817,0.731343,0.170089,0.273272,-1.449901,...,-0.113867,-1.482507,0.323217,2.423869,1.474208,1.228548,0.970635,0.840630,0.683688,NaN
20250818,0.531591,-0.722389,NaN,1.835994,NaN,-0.611248,0.784550,0.391816,0.135007,-1.265394,...,-0.235922,-1.428198,0.498787,2.407064,0.646254,-0.624145,0.308541,0.581360,0.548747,NaN
20250825,-0.004402,-1.497048,NaN,0.929760,NaN,-0.389316,0.936204,0.104206,0.419991,-1.453047,...,0.049829,-1.246028,1.937533,2.001983,-0.252630,-0.721186,0.113528,0.809375,0.667526,NaN
20250901,0.275659,-1.562736,NaN,-0.019229,NaN,-0.822951,0.664056,0.218805,0.127062,-1.507069,...,0.013669,-1.133233,1.772328,2.557721,-0.351107,-0.957238,0.035452,0.619086,0.514591,NaN
20250908,0.418474,-1.518710,NaN,-0.091636,NaN,-0.876127,1.004460,0.673327,-0.763917,-1.169185,...,-0.673327,-1.144755,0.987719,1.184932,-0.277104,-0.970509,0.178163,0.126128,-0.563891,NaN
20250915,0.318944,-1.362102,NaN,-0.171779,NaN,-0.027335,1.532151,0.232782,-0.845390,-0.694545,...,-0.898230,-1.017711,0.351778,1.186914,-0.508942,-0.792272,0.172719,0.147849,-0.595837,NaN
20250922,0.442022,-1.202996,NaN,-0.361652,NaN,-0.254735,1.826169,0.454314,-0.840104,-0.586458,...,-0.849370,-1.575523,0.353257,1.161076,-0.786579,-0.090456,0.214732,0.154409,-0.769026,NaN
20250929,0.644143,-0.762128,NaN,-0.266035,NaN,-0.844593,1.676559,0.223580,-1.323721,-0.678126,...,0.297343,-0.375244,1.254658,1.347438,0.391185,0.158043,0.402705,0.018054,0.671152,NaN
20251009,0.619988,-0.773453,NaN,-0.587774,NaN,-1.072669,1.320497,0.278713,-1.373225,-0.461831,...,0.333037,-0.384374,1.257821,1.349838,0.443373,0.282082,0.451045,0.040508,0.656298,NaN
20251013,0.651713,-0.710073,NaN,-0.903732,NaN,-1.382793,1.479404,0.237559,-1.246670,-0.382381,...,-0.682939,-0.622795,1.284820,2.290853,-0.544850,0.163405,1.166190,0.767227,-0.088282,NaN
20251020,0.673038,-0.647712,NaN,-1.108744,NaN,-1.560159,1.529632,0.082707,-0.966806,-0.591629,...,-0.412937,-0.222826,2.442488,2.534434,-0.684108,0.471637,0.775953,1.423670,0.731074,NaN
20251027,0.610782,-0.583686,NaN,-1.168241,NaN,-1.697954,1.580993,0.352535,-0.978936,-0.410761,...,0.406737,-0.187776,2.742852,2.919420,-0.343196,0.560256,0.846973,1.568207,0.899125,NaN
20251103,0.854673,-0.933999,NaN,-0.508970,NaN,-1.631672,0.139632,0.673764,-0.672604,-1.033787,...,0.287352,-0.292657,1.795992,2.583625,-0.573758,1.251241,0.380270,0.858009,0.998149,NaN
20251110,0.765845,-0.791503,NaN,-0.216338,NaN,-1.347209,-0.301426,0.589547,-0.467792,-0.780175,...,0.692880,-0.243862,1.897921,2.243115,-0.682343,1.455740,0.554171,0.922994,0.720764,NaN
20251117,0.727231,-0.325516,NaN,0.186425,NaN,-1.049131,-0.228935,-1.047530,-0.605418,-0.784433,...,0.714643,-0.170926,1.822281,2.523564,-0.555093,1.214873,0.733265,0.617119,1.023822,NaN
20251124,0.390426,-0.830807,NaN,0.458697,NaN,-0.579832,-0.263140,-1.078664,-0.427097,-1.013194,...,1.081977,-0.089294,1.618188,2.416554,-0.516993,1.061464,0.771571,0.595759,1.414432,NaN
20251201,0.270511,-0.733081,NaN,-0.120169,NaN,-0.306149,-0.435378,-0.932482,-0.349537,-0.949747,...,1.157316,0.174348,1.694756,2.992782,0.086727,1.136802,1.130653,0.673910,1.583344,NaN

In [16]:
all_cell_values = data.values.ravel()

unique_types = pd.unique(all_cell_values).tolist()
unique_types

['均衡', None, '金融地产', 'TMT', '医药', '制造', '消费', '周期']

In [70]:
# 填充异常缺失行
# data.loc['20250506':'20250513',:].dropna(axis=1,how="all")

# fill_series = data.loc['20250506']
# filled_df = pd.DataFrame([fill_series] * 3, 
#                          index=['20250507', '20250508', '20250509']) 
# data.loc[['20250507', '20250508', '20250509']] = filled_df
# data.loc['20250506':'20250513',:].dropna(axis=1,how="all")

,000001.SZ,000002.SZ,000009.SZ,000021.SZ,000027.SZ,000032.SZ,000034.SZ,000039.SZ,000050.SZ,000060.SZ,...,688567.SH,688578.SH,688599.SH,688617.SH,688772.SH,688777.SH,688778.SH,688819.SH,688981.SH,689009.SH
20250506,0.00396,0.00173,0.0006,0.00063,0.00034,0.00039,0.00087,0.00052,0.00037,0.00044,...,0.00033,0.00074,0.00053,0.00091,0.00032,0.00112,0.0003,0.00013,0.00662,0.00118
20250507,0.00396,0.00173,0.0006,0.00063,0.00034,0.00039,0.00087,0.00052,0.00037,0.00044,...,0.00033,0.00074,0.00053,0.00091,0.00032,0.00112,0.0003,0.00013,0.00662,0.00118
20250508,0.00396,0.00173,0.0006,0.00063,0.00034,0.00039,0.00087,0.00052,0.00037,0.00044,...,0.00033,0.00074,0.00053,0.00091,0.00032,0.00112,0.0003,0.00013,0.00662,0.00118
20250509,0.00396,0.00173,0.0006,0.00063,0.00034,0.00039,0.00087,0.00052,0.00037,0.00044,...,0.00033,0.00074,0.00053,0.00091,0.00032,0.00112,0.0003,0.00013,0.00662,0.00118
20250512,0.00396,0.00173,0.0006,0.00063,0.00034,0.00039,0.00087,0.00052,0.00037,0.00044,...,0.00033,0.00074,0.00053,0.00091,0.00032,0.00112,0.0003,0.00013,0.00662,0.00118
20250513,0.00396,0.00173,0.0006,0.00063,0.00034,0.00039,0.00087,0.00052,0.00037,0.00044,...,0.00033,0.00074,0.00053,0.00091,0.00032,0.00112,0.0003,0.00013,0.00662,0.00118

In [125]:
# # 检查下更新后是否有前面全是空值或最后两个都是空值的列，355只退市股票
# cond1 = data.iloc[:-108].isnull().all()
# cond2 = data.iloc[-2:].isnull().all()
# cond3 = data.columns.str.contains(r'\.BJ')
# mask = cond1 | cond2
# data0 = data.loc[:,mask]
# data0

,000003.SZ,000005.SZ,000013.SZ,000015.SZ,000018.SZ,000023.SZ,000024.SZ,000033.SZ,000038.SZ,000040.SZ,...,920018.BJ,920022.BJ,920027.BJ,920037.BJ,920056.BJ,920068.BJ,920100.BJ,920101.BJ,920112.BJ,T00018.SH
20000104,5.655702,6.135588,8.366522,5.512267,12.132206,9.259340,10.077100,6.896766,11.342393,8.024475,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000105,5.751758,6.319537,9.136277,5.642971,13.077659,9.456400,10.245781,7.126723,11.527209,8.336043,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000106,5.729135,6.317382,9.433637,5.695431,12.985868,9.487971,10.060000,7.317669,11.442442,8.429776,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000107,5.989354,6.653080,9.527855,5.739511,14.117200,9.883072,11.069188,7.534747,11.865176,9.099532,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000110,6.322865,6.933363,9.547081,5.850599,14.858114,10.174255,12.179698,7.847170,11.969637,9.139109,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000111,6.065231,7.027631,9.498567,5.716528,14.466696,9.918287,12.144747,7.907984,11.756409,9.866891,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000112,5.912483,6.576702,8.940434,5.412565,14.220369,9.445918,11.324065,7.557515,11.290653,9.428132,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000113,6.173306,6.503601,8.740866,5.474785,13.919418,9.326866,11.110110,7.569250,11.004894,8.691394,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000114,5.907730,6.557053,8.489320,5.403600,13.450383,9.255102,10.850550,7.571901,10.983108,8.310277,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000117,5.860406,7.172559,8.396847,5.090000,13.457877,9.168749,10.719849,7.461340,10.869636,8.283176,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000118,5.773668,7.592927,8.760840,4.958916,13.700000,9.143504,10.923339,7.270713,10.817938,8.432976,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000119,5.795762,7.296183,8.541681,4.958289,14.710190,9.010261,10.826560,7.574327,10.973057,8.432493,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000120,5.683538,7.617448,8.704780,5.055217,14.792404,9.105652,11.082578,7.986260,11.200093,8.511888,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000121,5.632707,7.722006,8.867961,4.833066,15.009200,9.003151,11.005448,7.681397,11.548674,9.051293,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000124,5.457485,7.838282,8.284699,4.585817,15.266760,8.551038,10.646321,7.405466,11.045920,9.005263,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000125,5.622564,7.915166,8.658076,4.612320,15.012430,8.810279,11.012655,7.510494,11.324919,9.272348,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000126,5.534591,7.563147,8.486567,4.790924,14.750670,8.803561,10.847328,7.568925,11.151091,9.119853,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000127,5.509223,7.551708,8.361763,4.686878,14.851935,8.971222,10.887467,7.510486,10.977720,9.339882,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000128,5.597673,7.960970,8.516383,4.478321,15.444316,9.475323,10.880000,7.332772,11.378495,9.647279,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000214,5.994102,8.885863,9.275222,4.611007,16.535576,10.759030,10.880000,7.977397,12.178679,10.409586,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000215,6.089373,9.464530,10.009166,4.830079,16.985720,11.839220,10.880000,8.548452,12.713337,11.527917,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000216,5.866130,9.209098,10.321483,4.585568,17.012176,13.019794,10.880000,9.027102,12.946721,12.587094,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000217,6.454767,9.712915,10.500251,4.579840,17.941385,14.320376,10.880000,9.615291,13.574184,13.577220,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000218,6.186277,8.596179,9.592707,4.771190,17.100432,15.749888,10.880000,8.552509,13.378097,13.299954,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000221,6.583212,8.625060,10.469671,5.011455,17.052981,17.329608,11.970772,8.227206,14.949053,15.036024,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000222,6.658891,8.409310,10.698400,5.319656,16.229987,18.847693,12.856613,8.281503,15.136061,14.374119,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000223,6.138150,8.081684,10.939718,5.216838,16.399953,17.941678,10.986089,8.588283,12.478381,12.638289,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000224,6.098758,8.095151,11.609386,4.866592,16.665930,15.870512,10.609603,9.162761,12.122318,12.141872,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000225,6.034831,7.937186,11.479062,4.907607,16.279732,17.646077,10.803522,9.624226,12.490948,12.337992,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20000228,6.133451,7.950798,12.458471,4.939066,15.951655,19.162930,10.747783,10.300612,12.519256,12.996948,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20250820,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40.413075,NaN,31.821044,101.886556,NaN,23.280213,NaN,53.639044,NaN,NaN
20250821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.588254,NaN,32.437271,99.608303,NaN,22.438737,NaN,53.464287,NaN,NaN
20250822,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,35.220679,NaN,31.223298,97.331556,33.854139,21.964693,NaN,52.245798,NaN,NaN
20250825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34.486221,NaN,31.429878,97.692083,29.920932,22.573436,NaN,52.277153,NaN,NaN
20250826,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,35.430619,NaN,31.802115,99.398524,33.381343,21.307967,NaN,52.661940,NaN,NaN
20250827,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34.167112,NaN,31.000768,95.439572,31.099928,21.067872,NaN,51.472745,NaN,NaN
20250828,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.385878,NaN,30.189048,92.560848,29.641783,20.765180,NaN,50.476135,47.961974,NaN
20250829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.292725,NaN,30.655945,93.867729,29.566345,21.061773,NaN,50.995490,46.121543,NaN
20250901,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.149337,NaN,30.025677,93.614395,29.316756,21.395438,NaN,50.299874,44.045167,NaN
20250902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.304779,NaN,29.948248,94.965107,29.478007,20.941873,NaN,50.547613,43.512498,NaN
20250903,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.437946,NaN,29.981976,91.037287,30.586708,20.541961,NaN,50.752034,43.255877,NaN
20250904,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.514793,NaN,30.055842,87.207251,31.422680,20.375257,NaN,50.328121,43.679977,NaN
20250905,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.721314,NaN,30.496835,87.447458,32.643323,20.769987,NaN,50.918030,43.789906,NaN
20250908,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.749383,NaN,30.725202,89.882694,31.733894,20.975546,73.888066,51.547478,44.382284,NaN
20250909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.430245,NaN,30.281630,91.314373,30.831125,20.840235,78.593257,50.273583,43.337361,NaN
20250910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.921527,NaN,30.104658,88.418207,30.178750,20.460931,80.642989,49.489025,42.595638,NaN
20250911,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.839640,NaN,30.231398,88.340705,30.379403,20.504198,85.962001,49.659729,42.439151,NaN
20250912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.767262,NaN,30.462164,87.799390,29.845660,20.684970,84.962029,49.571737,42.416979,NaN
20250915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.903194,NaN,29.928507,86.497402,30.133354,20.342930,88.008491,48.679000,42.244800,NaN
20250916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.675331,NaN,29.850533,86.785789,29.704904,20.122963,90.870508,48.029000,42.413532,NaN
20250917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.636571,NaN,29.967474,89.978456,29.651281,20.217313,89.058361,48.206115,42.299910,NaN
20250918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.500883,NaN,29.694818,88.329949,30.045941,20.071975,84.208038,48.017437,42.233136,NaN
20250919,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,31.801983,44.106741,29.339603,86.629707,29.499534,19.901983,80.342556,48.689600,41.175100,NaN
20250922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,31.109247,36.002140,28.810305,86.234819,28.473612,19.546884,78.875365,46.923564,40.394030,NaN
20250923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.159664,34.314556,27.805027,90.708065,27.087875,18.849151,78.138680,45.142533,39.138172,NaN
20250924,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.866265,33.876468,27.846669,90.220823,27.114089,19.242504,78.127616,44.945042,39.516033,NaN
20250925,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.507305,33.422260,27.559191,93.133229,26.890120,18.899681,77.053418,44.612571,39.831938,NaN
20250926,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.912247,34.359285,27.602915,94.903608,27.935314,18.808829,72.355563,45.119306,40.547526,NaN
20250929,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.283763,32.513377,27.504499,95.724443,27.365486,18.851313,71.192516,44.334609,39.770966,NaN
20250930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.532938,32.076732,27.789117,93.225135,27.153577,19.095903,70.183993,44.334613,39.413836,NaN

In [79]:
## 更新表、存表
# FactorData = data_final
# # FactorData.index.name=None
# FactorData.index = FactorData.index.astype(str)
# #FactorData = FactorData.rolling(window=3,min_periods=1).mean()

# MainQSEnv.FactorDB.saveFactor(
#     factor_data = FactorData,
#     table_name='ElementaryFactor',
#     factor_name= '最低价',
#     if_exists='replace')
# #     data_type=None)

1

In [22]:
## 删除因子/因子表
# 删除因子表
# 谨慎使用
# MainQSEnv.FactorDB.deleteTable('TestGenFactor')
# 删除指定因子
# 谨慎使用
MainQSEnv.FactorDB.deleteFactor(
    table_name='StyleFactorM',
    factor_names=['StyleFactorM'])
'''
即使仅删除单个因子，也必须以list形式输入参数。
无论因子是否成功删除，该函数都会返回1，请运行结束后再次读取因子确认成功删除。
'''

'\n即使仅删除单个因子，也必须以list形式输入参数。\n无论因子是否成功删除，该函数都会返回1，请运行结束后再次读取因子确认成功删除。\n'

In [ ]:
start_date = '20180101'
end_date = '20251025'
d1 = getWeekFirstDay(MainQSEnv.FactorDB.getFactorDate("ElementaryFactor", price_type, start_date, end_date))

In [ ]:
# 风险数据库

In [3]:
RiskTable = MainQSEnv.FRDB.getTableName()
print(RiskTable)

['BarraRiskData', 'BarraRiskDataOLD']

In [ ]:
# 获取风险数据库日期
MainQSEnv.FRDB.getTableDate('BarraRiskData')
'''
平台的Barra因子协方差矩阵以月频计算，getTableDate返回每个月最后一个交易日
'''

# 获取风险数据库因子收益日期
dates = MainQSEnv.FRDB.getFactorReturnDate('BarraRiskData')

# 获取风险数据库特异性收益日期
MainQSEnv.FRDB.getSpecificReturnDate('BarraRiskData')
'''
因子收益和特异性收益为日频
'''

# 获取风险数据库因子ID
MainQSEnv.FRDB.getTableID('BarraRiskData')

In [10]:
dates = MainQSEnv.FRDB.getFactorReturnDate('BarraRiskData')[-500:] # -463:20240102
FactorExposure = MainQSEnv.FRDB.loadFactorReturn('BarraRiskData',dates=dates )
pq.write_table(pa.Table.from_pandas(FactorExposure),'BarraRiskDataReturn2425add.pqt')
FactorExposure

,Market,Size,Beta,Momentum,ResidualVolatility,NonlinearSize,BookToPrice,Liquidity,EarningsYield,Growth,...,Food Staples Retail Household Personal Prod,Beverages,Food Products,Health,Banks,Diversified Financial Services,Real Estate,Software,Hardware and Semiconductors,Utilities
20231109,-0.000571,0.001336,0.000182,-0.000702,0.000008,-0.002669,0.000078,-0.002610,0.002932,0.001069,...,0.001174,0.001298,0.002010,-0.005629,-0.007515,-0.000488,-0.002336,0.004461,-0.000776,0.003989
20231110,-0.006226,-0.001717,-0.002218,0.000363,-0.002898,-0.000089,-0.000395,0.000572,-0.000630,0.000426,...,0.010676,-0.008504,0.000671,0.004094,0.001833,0.004819,-0.004555,-0.008871,0.002212,0.009426
20231113,0.003007,-0.002748,0.000433,0.000471,-0.000032,-0.002229,0.001738,0.001652,-0.001059,-0.000236,...,-0.008849,-0.006691,-0.004897,-0.010706,-0.005780,-0.008294,-0.007154,0.015322,0.002425,-0.002202
20231114,0.002104,-0.000876,0.001650,0.000495,0.001623,0.004056,0.000241,0.000468,-0.001313,-0.000077,...,0.003168,-0.001803,-0.000769,-0.002926,0.006560,0.007241,0.008063,0.009650,0.003168,-0.004358
20231115,0.005308,-0.000178,0.000835,-0.000897,0.000156,-0.000893,-0.000495,-0.000490,0.001533,0.000212,...,-0.006575,0.002211,-0.001300,-0.000898,-0.005282,0.000101,-0.010135,-0.008649,-0.002782,0.000593
20231116,-0.008814,-0.000879,-0.002303,0.002806,-0.000964,-0.002154,0.000203,-0.001446,-0.000113,-0.000805,...,-0.000744,-0.000622,-0.000449,-0.003193,0.001108,0.001089,0.003700,0.007863,-0.001570,-0.001050
20231117,0.001562,-0.002315,0.001219,0.000667,-0.000153,0.000901,-0.001319,-0.000987,0.000425,-0.000096,...,-0.001936,-0.006660,-0.006330,0.007040,-0.002620,-0.000697,-0.007993,-0.006226,0.000463,-0.001228
20231120,0.003478,-0.001809,0.000073,-0.000522,0.000568,-0.000195,-0.000614,0.000776,-0.000677,-0.001011,...,-0.000156,0.001558,0.005925,0.002788,0.005301,-0.007629,-0.003800,0.000135,-0.004114,-0.003395
20231121,-0.002037,0.001103,-0.000055,-0.000309,-0.000008,-0.002590,0.001276,-0.002771,0.000739,-0.000726,...,0.008905,0.017062,0.004106,0.005167,-0.005313,0.001495,0.023336,-0.003741,-0.006835,-0.001236
20231122,-0.010048,-0.000190,-0.003987,0.001149,-0.003321,-0.002986,-0.000197,-0.000464,0.000300,-0.000451,...,0.005403,0.005936,0.007464,0.004418,-0.001534,0.001153,0.009918,0.008906,-0.002668,-0.002342
20231123,0.007953,-0.001189,0.001126,0.001160,-0.001307,0.001534,0.000543,-0.000653,0.000744,0.000033,...,-0.002827,-0.005210,-0.005099,0.005727,-0.011982,-0.006626,0.007936,-0.007249,0.004366,-0.002920
20231124,-0.007641,0.001265,-0.003060,0.000962,-0.001751,-0.000827,0.000550,-0.002320,0.000669,-0.000576,...,0.014548,0.006410,0.014429,0.015475,-0.004239,-0.001773,0.004302,-0.009620,-0.004768,-0.002551
20231127,-0.003620,-0.000493,0.000243,0.003744,-0.002127,0.001267,-0.001083,-0.000733,-0.001445,0.000336,...,-0.006370,-0.014071,-0.000525,-0.011599,0.007092,-0.007118,-0.015886,0.000657,0.007769,0.004083
20231128,0.002886,-0.001037,0.001208,-0.001087,-0.001542,-0.001864,-0.000229,0.000071,-0.000533,0.000258,...,0.000930,-0.008682,-0.005260,0.005820,-0.000889,-0.005607,-0.012738,-0.005892,-0.000927,0.001039
20231129,-0.007713,0.000144,-0.000071,0.002402,-0.000989,0.000922,-0.002224,-0.001827,-0.000187,0.000204,...,-0.000576,0.000809,0.002267,-0.005159,0.004487,-0.000138,-0.008927,-0.005279,0.002667,0.002122
20231130,0.001276,0.002937,-0.000843,0.001660,0.001031,-0.001605,0.000399,-0.001286,-0.000312,0.000255,...,0.007566,0.006346,0.009434,0.009616,0.000108,0.005122,0.003837,-0.002285,-0.006681,0.007084
20231201,0.001432,-0.001889,0.002883,0.002293,0.001758,0.001448,0.002511,0.000661,-0.000752,-0.000112,...,-0.000831,-0.008465,-0.007837,-0.001386,0.000642,0.001009,0.003187,0.024888,-0.000071,0.002550
20231204,-0.003168,-0.001085,-0.001710,0.002015,-0.001230,-0.002180,-0.000134,0.000589,-0.000662,-0.000045,...,-0.006062,-0.012898,-0.002698,-0.010814,0.001103,0.000734,-0.007795,0.010727,-0.001975,-0.001216
20231205,-0.017410,0.000190,-0.002157,0.000563,0.000164,-0.001444,-0.000099,-0.001972,0.000126,0.000452,...,0.007443,-0.000375,0.014296,0.009289,-0.000736,0.007109,-0.000449,-0.012196,-0.007183,0.002227
20231206,0.001897,-0.000754,0.001766,-0.002345,-0.001022,-0.001954,-0.000676,0.000432,0.000057,0.000614,...,-0.006323,0.000781,0.005531,-0.000875,-0.002772,-0.005681,0.009058,0.002080,-0.005092,-0.001614
20231207,-0.001367,0.000969,0.003517,0.002792,-0.002049,0.001522,0.001138,-0.001395,0.000088,0.000156,...,0.000088,0.001001,0.003338,-0.006184,0.000214,0.006048,0.006145,0.019912,0.001484,0.004028
20231208,0.003235,0.006099,0.003987,0.001151,-0.000134,0.005630,0.000021,0.000385,-0.000464,0.000590,...,-0.003140,-0.004132,-0.009136,0.005353,0.001416,-0.012549,-0.014520,0.004406,0.012042,0.013060
20231211,0.008864,-0.000437,0.000053,0.002328,-0.000814,0.002910,-0.001766,-0.000349,0.000471,0.000120,...,0.001089,-0.019770,-0.007988,-0.005876,0.002228,0.011160,-0.006150,0.004763,0.000652,0.001384
20231212,0.002460,-0.001019,-0.001874,0.001567,-0.000348,-0.001900,0.000974,0.000373,0.000056,-0.000698,...,0.000432,0.009586,0.000632,-0.003106,-0.000988,-0.005565,0.019430,0.000909,-0.001117,-0.002614
20231213,-0.012732,-0.001894,-0.002127,0.002978,-0.003445,-0.001032,-0.000201,-0.000842,-0.001250,-0.000206,...,-0.006179,-0.018848,-0.012306,0.009609,0.004965,-0.000322,-0.006539,-0.004048,-0.001511,0.007169
20231214,-0.004458,-0.000144,0.000039,-0.000742,-0.001891,-0.001416,-0.000182,-0.002204,-0.000162,0.000202,...,0.002145,-0.013579,-0.003503,-0.003481,0.000336,0.000711,0.004795,-0.002711,-0.001186,0.008395
20231215,-0.005429,-0.000547,0.000632,-0.002078,-0.000715,-0.003312,-0.000303,0.001362,0.000768,0.000098,...,-0.000395,0.006242,0.003634,-0.009300,-0.002170,0.005156,0.012204,-0.001107,-0.002448,-0.004764
20231218,-0.007321,0.003044,-0.001165,0.004009,-0.000344,-0.003364,-0.000021,-0.001237,0.000771,-0.000190,...,0.001544,0.000481,0.002109,0.007936,0.002490,0.004275,-0.000206,-0.004076,-0.004591,0.000043
20231219,0.000196,0.000021,0.002209,0.000338,-0.001052,-0.002122,-0.000938,0.000245,0.000678,0.000192,...,-0.003550,0.002595,-0.001201,-0.005531,0.001198,-0.005002,-0.010277,0.005532,0.005740,-0.006200
20231220,-0.010734,-0.000522,-0.003971,-0.000237,-0.002899,-0.004463,0.000048,0.001592,0.001606,0.000104,...,0.002330,-0.005129,-0.006040,0.002165,-0.000706,-0.012260,-0.003656,-0.010910,0.003248,0.005634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20251021,0.013586,-0.000170,0.003221,0.004505,-0.000925,-0.003479,0.000562,-0.001856,-0.000445,-0.000165,...,-0.001980,-0.008523,0.000547,-0.003157,-0.008716,-0.001992,0.011963,-0.003687,0.005453,-0.002218
20251022,-0.003881,-0.000706,-0.001115,0.001673,-0.001071,-0.002911,0.000043,-0.001992,0.000014,-0.000422,...,0.000547,0.001705,-0.005016,0.001679,0.008849,-0.006235,0.012678,-0.000936,0.000751,-0.005472
20251023,0.002238,0.000080,-0.002178,-0.000649,-0.005543,-0.001153,-0.000128,-0.000241,0.000879,-0.000377,...,0.001481,-0.002485,-0.002487,-0.008247,-0.005774,0.003580,-0.013098,0.007754,-0.001619,0.002064
20251024,0.009486,0.002870,0.007344,0.003295,-0.000792,0.000133,-0.001261,0.000892,0.001431,0.000937,...,-0.005181,-0.015506,-0.000993,-0.004292,0.002889,-0.001584,-0.010340,-0.005436,0.011827,-0.003392
20251027,0.013563,0.002113,0.003316,0.000336,0.002174,0.000688,0.000559,0.001181,0.001710,0.000925,...,0.002632,-0.006200,0.003588,-0.000053,-0.013971,-0.001776,-0.010565,-0.005910,0.005842,0.003426
20251028,-0.005673,-0.001431,0.000115,0.000746,-0.000151,-0.000572,-0.001181,-0.001556,-0.001301,-0.001129,...,-0.007405,-0.000611,-0.001719,-0.002442,0.009386,-0.001961,-0.000990,0.004555,-0.000294,-0.002422
20251029,0.016112,0.003806,0.006625,-0.000500,0.003549,0.001827,0.000402,-0.000595,0.002794,0.000627,...,-0.005583,-0.012020,0.004216,-0.001438,-0.035613,0.006184,0.001298,-0.005485,-0.004571,0.003841
20251030,-0.007655,0.001928,0.000334,-0.005017,-0.000301,-0.001210,0.000639,-0.000836,-0.000017,-0.000333,...,-0.003621,0.005646,0.001722,-0.001297,-0.000040,-0.015722,-0.009058,0.000967,-0.003599,0.002992
20251031,-0.008517,-0.005705,-0.001746,-0.001185,0.000997,0.000456,-0.001284,-0.000555,-0.001665,-0.000858,...,-0.004199,0.010404,0.002658,0.018582,0.015324,-0.002711,0.000232,0.015018,-0.014802,-0.010374
20251103,0.002697,-0.001138,-0.002167,-0.005661,0.002260,-0.001011,0.000646,0.001558,-0.001169,-0.000043,...,-0.009830,-0.005877,0.001141,-0.003181,0.003551,-0.006865,-0.010499,0.008906,0.002946,-0.002379
20251104,-0.011389,-0.001091,-0.005220,-0.003605,0.000171,-0.002394,0.000371,0.000872,-0.000889,-0.001080,...,-0.003924,-0.006470,-0.005057,-0.008055,0.019937,0.006931,0.001902,-0.000336,0.002611,0.004534
20251105,0.002275,-0.001814,-0.000704,-0.001629,0.000591,-0.001128,0.000027,0.000334,0.000307,0.000353,...,-0.003521,-0.004210,-0.000268,-0.005237,-0.009678,-0.007669,-0.003500,-0.012653,-0.002290,0.002177
20251106,0.013447,0.002795,0.003424,0.005688,-0.003652,0.001345,0.000826,-0.001286,0.002735,0.000753,...,-0.007398,-0.006192,0.000263,-0.005458,-0.017276,-0.004834,-0.003818,-0.009170,0.003498,0.004523
20251107,-0.000145,0.000686,-0.001205,-0.003156,-0.000336,0.000336,0.001603,-0.000033,-0.000168,0.000193,...,0.001484,-0.004613,-0.000039,-0.001065,-0.011933,-0.010415,-0.005284,-0.011809,-0.001083,-0.003342
20251110,0.005737,-0.000208,-0.001928,-0.005976,0.002736,0.000445,-0.000116,-0.000391,-0.000627,0.000082,...,0.019089,0.026289,0.013965,0.005582,-0.005844,0.007743,0.000270,0.001935,-0.000875,-0.008364
20251111,-0.007328,-0.003408,-0.003406,-0.001332,0.000813,-0.000152,0.001216,-0.000053,-0.001921,-0.000115,...,0.005282,0.002849,0.006035,0.001589,0.004383,-0.004847,0.003867,-0.008601,-0.003043,-0.001825
20251112,-0.004012,0.000366,-0.000715,0.001441,-0.001529,-0.002884,-0.001109,-0.001552,0.002517,0.000462,...,0.012281,0.004295,0.001105,0.011920,0.002315,0.000068,0.004648,-0.000820,-0.000926,-0.000650
20251113,0.010718,0.001017,0.002461,-0.000906,0.001764,0.000817,0.000730,0.001865,-0.001908,0.000448,...,-0.003963,0.000274,-0.000166,0.000929,-0.005370,-0.000080,-0.003596,-0.002268,-0.007537,-0.007792
20251114,-0.014249,-0.003423,-0.005467,-0.001324,0.000138,-0.001615,0.000212,-0.001139,-0.002142,-0.001275,...,-0.002691,-0.009385,-0.009141,0.007298,0.009439,0.001323,0.002300,-0.005538,-0.001121,0.003385
20251117,-0.004780,-0.000479,0.000297,-0.002676,0.000880,0.001162,0.000259,0.002606,-0.004365,-0.001478,...,-0.008465,-0.001628,0.001218,-0.017549,0.005148,-0.005541,0.005774,0.013877,0.000387,-0.002377
20251118,-0.010205,0.001550,-0.000133,0.002540,-0.004786,-0.001588,-0.002405,-0.002222,-0.000037,0.000412,...,0.009293,0.000092,-0.000663,0.001082,0.014592,0.009246,-0.002924,0.020911,0.006037,-0.001521
20251119,0.001083,0.004535,-0.001142,0.000450,0.000065,0.000970,-0.000132,-0.001101,0.002178,-0.000197,...,0.007233,-0.004012,0.010802,-0.006806,-0.001714,-0.000492,-0.010676,-0.005536,-0.002815,-0.001807
20251120,-0.007497,-0.000137,-0.001968,0.002634,-0.004394,0.000257,-0.000552,-0.000583,0.000478,-0.000048,...,-0.015171,0.000239,-0.010357,0.001015,0.017866,0.003214,0.014300,0.000301,0.001174,0.003284
20251121,-0.026194,0.003611,-0.004022,0.000064,-0.002255,0.002778,-0.003643,-0.004178,0.002657,-0.001089,...,0.002705,0.003132,0.005996,-0.000889,0.005260,-0.003595,0.006667,0.015421,-0.002135,-0.003238
20251124,0.002339,-0.003709,0.000899,-0.000509,0.000009,0.000028,-0.001147,0.000021,-0.001015,-0.000455,...,-0.011855,-0.009079,-0.008933,-0.001016,0.002897,-0.001365,-0.005226,0.019606,0.002193,-0.009152
20251125,0.008220,-0.001271,0.003852,0.000971,0.002827,-0.001172,0.000926,0.001615,0.001134,-0.000179,...,0.002884,0.000026,-0.003083,0.003075,0.007529,-0.002525,0.000080,0.000979,0.003472,0.002887
20251126,0.002096,0.002173,0.001519,0.004467,-0.000145,0.001033,0.000677,-0.001211,0.000120,0.001034,...,0.012282,0.008002,0.005025,0.009672,-0.008228,-0.004568,-0.003910,-0.005732,0.001755,0.001832
20251127,-0.001679,-0.001155,0.001429,0.000459,-0.002062,-0.001602,-0.000435,-0.000852,0.001028,0.000084,...,-0.006228,0.000299,-0.002149,-0.001932,0.007910,-0.000065,-0.000211,-0.012061,0.001598,0.004866
20251128,0.004908,-0.001952,-0.000076,0.002288,-0.000611,0.000591,0.000484,0.000512,-0.002281,0.001145,...,-0.007147,-0.001286,0.004978,-0.007843,-0.003924,-0.000756,-0.002818,-0.003409,-0.000237,-0.002116
20251201,0.008433,0.000520,-0.000105,-0.000578,-0.003649,-0.000644,-0.001876,0.002027,0.002013,0.000388,...,-0.000570,-0.003018,-0.003725,-0.003372,0.004304,-0.007493,-0.001194,-0.005021,0.005312,-0.002847

In [ ]:
# 获取风险数据库股票Cov矩阵
MainQSEnv.FRDB.loadCov('BarraRiskData',dates='20221230')

# 获取风险数据库股票Cov矩阵
MainQSEnv.FRDB.loadFactorCov('BarraRiskData',dates='20051230')

# 读取股票特质风险
MainQSEnv.FRDB.loadSpecificRisk('BarraRiskData',dates='20051230')
'''
以上数据为月频（月末）
'''

# 读取因子数据
MainQSEnv.FRDB.loadFactorData('BarraRiskData',dates='20051230')

# 读取因子收益率数据
MainQSEnv.FRDB.loadFactorReturn('BarraRiskData',dates='20051230')

# 读取特质收益率数据
MainQSEnv.FRDB.loadSpecificReturn('BarraRiskData',dates='20051230')
'''
以上数据为日频
'''

In [12]:
MainQSEnv.FRDB.loadFactorData('BarraRiskData',dates='20231229')[-200:]

,Market,Size,Beta,Momentum,ResidualVolatility,NonlinearSize,BookToPrice,Liquidity,EarningsYield,Growth,...,Food Staples Retail Household Personal Prod,Beverages,Food Products,Health,Banks,Diversified Financial Services,Real Estate,Software,Hardware and Semiconductors,Utilities
920208.BJ,1.0,-3.145420,-0.401128,0.078007,-0.252744,-0.653000,-1.240363,0.425442,-0.127392,0.156906,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920212.BJ,1.0,-3.382770,-1.914962,0.648062,3.438894,-3.012964,-1.154616,0.387087,-1.118701,-0.872735,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920221.BJ,1.0,-3.346996,-0.081919,1.025042,0.467078,-2.404523,-1.370625,1.953502,-1.433204,0.879578,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920223.BJ,1.0,-3.472626,-3.304561,0.758854,3.216616,-4.853963,-1.015162,0.765275,-1.621933,-0.579530,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920225.BJ,1.0,-3.285683,-2.019942,3.357347,2.668424,-1.513947,-1.274590,0.036813,-0.690425,-0.619435,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920227.BJ,1.0,-3.415655,-3.109851,1.008685,2.815757,-3.633346,-1.012486,1.142061,-1.630608,0.137923,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920230.BJ,1.0,-3.434950,-3.305111,0.361822,2.858988,-4.025621,-0.942493,0.938635,-1.395166,0.368153,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920237.BJ,1.0,-3.473615,-2.950614,0.331217,2.766730,-4.876853,-0.581922,-0.339386,-1.520502,0.012616,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920239.BJ,1.0,-3.273698,-1.012937,-2.569936,3.224333,-1.361247,-1.040536,0.287562,-2.769976,0.345275,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920242.BJ,1.0,-3.398449,-2.693221,2.875902,2.877227,-3.301299,-0.938131,0.121031,-0.899173,-1.408141,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920245.BJ,1.0,-3.524543,-2.863255,0.154006,1.245013,-6.136482,-0.643914,-0.759825,-1.096380,0.152203,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920247.BJ,1.0,-3.258634,-3.603015,0.939767,3.804684,-1.178813,-1.515063,1.720565,-1.681667,-0.918972,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920249.BJ,1.0,-3.206625,-2.605014,0.523194,2.865133,-0.771906,-1.250243,0.964862,-1.462317,0.574047,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920252.BJ,1.0,-3.404184,-1.631530,0.729967,2.681739,-3.410138,-1.400773,1.867086,-1.565761,-0.480925,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920260.BJ,1.0,-3.449859,-3.199786,1.573455,1.267497,-4.343399,-0.823417,0.112709,-1.012196,-0.775097,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920261.BJ,1.0,-3.233511,-0.117871,-0.101601,-0.363136,-0.897518,-0.584080,-1.043297,-1.161568,-1.251223,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920262.BJ,1.0,-3.477051,-3.285324,-0.144891,2.859155,-4.956820,-0.954065,1.150644,-0.389373,0.066239,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920263.BJ,1.0,-3.428995,-1.963757,1.164899,1.225578,-3.902271,-0.646881,-0.703896,-0.509342,-0.792217,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920266.BJ,1.0,-3.413711,-2.482990,0.737487,0.536152,-3.595005,0.488804,-1.144703,-1.036663,-0.401138,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920267.BJ,1.0,-3.455537,-2.814099,0.788061,2.821796,-4.467860,-1.234687,0.191715,-0.662194,-0.318524,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920270.BJ,1.0,-3.381780,-3.223015,0.619365,2.981894,-2.995200,-1.168401,0.859417,-0.928225,-0.160541,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920271.BJ,1.0,-3.299931,-3.250523,0.979621,3.078895,-1.704387,-1.315416,0.261551,-0.874165,-0.234404,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920273.BJ,1.0,-3.419115,-3.424122,0.456019,3.005929,-3.702143,-0.563925,0.305184,-0.334629,-0.295770,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920274.BJ,1.0,-3.420644,-1.060016,0.795330,0.265581,-3.732741,-0.686075,1.906989,-1.658878,-0.816900,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920275.BJ,1.0,-3.494605,-3.256083,0.388498,2.819557,-5.376511,-1.161907,-0.378442,-1.204243,-1.365588,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920278.BJ,1.0,-3.364698,-3.478613,1.865461,2.975068,-2.697116,-1.257744,0.329098,-1.044700,-1.020704,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920284.BJ,1.0,-3.371841,-0.280532,0.604104,0.106824,-2.819864,-1.454084,0.051178,-1.339767,1.130668,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920299.BJ,1.0,-3.497845,-3.241140,0.835921,2.979405,-5.456049,-0.962401,0.862717,-1.029811,-1.830511,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920300.BJ,1.0,-3.393799,-3.290042,0.350703,3.138421,-3.214378,-1.343706,0.807184,-1.766085,-0.170384,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920304.BJ,1.0,-3.347962,-0.246871,0.121945,-0.367283,-2.420059,-1.224597,0.865070,-1.333705,0.531204,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
920879.BJ,1.0,-3.352215,-1.761339,0.671177,0.995835,-2.489088,-1.042610,-0.320208,-0.978687,0.279040,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920885.BJ,1.0,-3.347832,-3.295410,1.015802,3.410404,-2.417977,-1.349509,0.495909,-1.387945,-0.228677,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920892.BJ,1.0,-3.331090,-2.138831,1.077181,2.820735,-2.155431,-1.402907,-1.015026,-0.529138,-0.552566,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920895.BJ,1.0,-3.490455,-0.548095,0.786230,0.188909,-5.275590,-1.213623,1.599264,-1.416145,-0.349858,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920896.BJ,1.0,-3.402915,-0.157697,1.079007,0.503556,-3.385903,-1.083950,1.661444,-1.273109,-0.273898,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920906.BJ,1.0,-3.388795,-3.220806,1.065381,3.355196,-3.122176,-0.846585,1.633455,-1.188828,0.599557,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920914.BJ,1.0,-3.396322,-2.790715,0.094876,1.250971,-3.261382,-0.048477,-0.091315,-1.462801,0.566511,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920924.BJ,1.0,-3.451956,-2.749317,1.903195,2.853145,-4.389154,-1.203206,-0.152301,-1.274796,0.478101,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920925.BJ,1.0,-3.410470,-2.952013,1.769979,1.704541,-3.531546,-1.099878,-0.284955,-0.959753,-2.070845,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920926.BJ,1.0,-3.484216,-0.193829,0.552012,-0.171211,-5.125838,-1.097694,1.496638,-0.952537,-0.009129,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920931.BJ,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920932.BJ,1.0,-3.385602,-3.206090,1.516619,1.663054,-3.064053,-0.657082,-0.142863,-0.852644,-0.043325,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920942.BJ,1.0,-3.495903,-3.212666,0.794595,0.577217,-5.408297,-0.377565,-0.520846,-1.445868,-0.817999,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920943.BJ,1.0,-3.358229,-2.665389,0.583204,2.883798,-2.588291,-0.999858,0.321514,-0.681656,-0.238913,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920946.BJ,1.0,-2.877632,-3.254884,0.620716,2.814830,-0.203668,-1.235246,-0.963796,-1.028028,-0.852286,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920950.BJ,1.0,-3.439607,-3.215521,0.770040,2.966409,-4.123497,-1.281874,0.843173,-0.866909,0.036006,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920953.BJ,1.0,-3.337344,0.261486,0.892007,0.805916,-2.251826,-1.186916,1.969989,-1.606668,0.084119,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920957.BJ,1.0,-3.456750,-3.277663,0.334432,2.884679,-4.494696,-0.844538,0.320913,-1.497326,-0.232056,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920961.BJ,1.0,-3.313150,-3.156462,0.735389,2.933775,-1.889864,-0.909561,-0.294308,-1.056156,-0.503844,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920964.BJ,1.0,-3.428472,-3.286362,0.155677,1.720970,-3.891551,0.336020,0.029312,-1.371499,-0.180839,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920970.BJ,1.0,-3.504417,-2.909606,0.588433,2.933344,-5.619404,-0.798808,0.310578,-1.359842,0.020534,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920971.BJ,1.0,-3.339780,-3.303600,0.037154,3.205662,-2.289910,-1.237662,1.281072,-1.446626,0.084475,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920974.BJ,1.0,-3.362208,-1.711197,0.149770,3.049016,-2.654968,-0.766196,-0.245393,-1.355132,-0.121699,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920976.BJ,1.0,-3.462642,0.149493,0.796098,0.411788,-4.626271,-1.206363,1.849750,-0.932204,0.097682,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920978.BJ,1.0,-3.239986,0.063094,0.921770,0.397270,-0.967314,-1.378375,1.452184,-1.031583,0.554759,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920981.BJ,1.0,-3.386155,-2.552072,0.786012,2.085185,-3.074065,-0.921771,0.086713,-1.103507,-2.021544,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920982.BJ,1.0,-1.407610,-0.149443,0.208255,0.028742,0.608236,-1.855093,0.019814,-1.721829,0.627362,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920985.BJ,1.0,-3.244976,-0.718643,0.003920,2.457096,-1.022377,-0.656792,0.496963,-1.134170,1.400584,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920992.BJ,1.0,-3.406825,-3.217131,0.354222,3.323137,-3.460871,-0.584672,0.994786,-1.268753,0.375599,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
T00018.SH,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.407158,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
# 读取股票特质风险
MainQSEnv.FRDB.loadSpecificRisk('BarraRiskData',dates='20051230')[-200:]

920208.BJ         NaN
920212.BJ         NaN
920221.BJ         NaN
920223.BJ         NaN
920225.BJ         NaN
920227.BJ         NaN
920230.BJ         NaN
920237.BJ         NaN
920239.BJ         NaN
920242.BJ         NaN
920245.BJ         NaN
920247.BJ         NaN
920249.BJ         NaN
920252.BJ         NaN
920260.BJ         NaN
920261.BJ         NaN
920262.BJ         NaN
920263.BJ         NaN
920266.BJ         NaN
920267.BJ         NaN
920270.BJ         NaN
920271.BJ         NaN
920273.BJ         NaN
920274.BJ         NaN
920275.BJ         NaN
920278.BJ         NaN
920284.BJ         NaN
920299.BJ         NaN
920300.BJ         NaN
920304.BJ         NaN
               ...
920879.BJ         NaN
920885.BJ         NaN
920892.BJ         NaN
920895.BJ         NaN
920896.BJ         NaN
920906.BJ         NaN
920914.BJ         NaN
920924.BJ         NaN
920925.BJ         NaN
920926.BJ         NaN
920931.BJ         NaN
920932.BJ         NaN
920942.BJ         NaN
920943.BJ         NaN
920946.BJ         NaN
920950.BJ         NaN
920953.BJ         NaN
920957.BJ         NaN
920961.BJ         NaN
920964.BJ         NaN
920970.BJ         NaN
920971.BJ         NaN
920974.BJ         NaN
920976.BJ         NaN
920978.BJ         NaN
920981.BJ         NaN
920982.BJ         NaN
920985.BJ         NaN
920992.BJ         NaN
T00018.SH    0.097898
dtype: float64